### ISSUE TITLE
Port for Solid JS

### ISSUE THREAD

**Issue by nonphoto** [portabletext/portabletext#21]
I ported @portabletext/react to Solid. It's very "alpha" but it's working fine in a client project I have. Is there any interest in publishing this in the portable text org?

**Comment by kmelve** [comment]
Awesome! Yes, we‘d totally welcome the contribution and invite you to the Portable Text organization. Let us know when you feel it’s ready!

**Comment by nonphoto** [comment]
I uploaded it here: https://github.com/nonphoto/solid-portabletext. I’m not sure what your build process is for libraries so I just used vite and called it a day; it should work once library mode is configured.

**Comment by stipsan** [comment]
[Done](https://github.com/portabletext/solid-portabletext), I've invited you to the repo as a collaborator @nonphoto 💖 
And released the first version: https://www.npmjs.com/package/@portabletext/solid/v/1.0.0
