### ISSUE TITLE
Editor support?

### ISSUE THREAD

**Issue by Starefossen** [portabletext/portabletext#31]
Are there any open source editors that support outputting portabletext such as https://lexical.dev/, https://www.blocknotejs.org/ or https://editorjs.io/? All the info I could find was on the presentation side and not on the editing side. Maybe I misunderstood something? 🤔

**Comment by CanRau** [comment]
Brought it up here, though pretty silent 😅 
Tho someone could still come up with a plugin or just a package that converts lexical state to portabletext of course.

Not sure you saw/know that protabletext is currently only (I think) used & build by the headless cms https://sanity.io

**Comment by Starefossen** [comment]
Thanks @CanRau, I have seen Sanity mentioning Portable Text in a blog post, that sort of explains why this is only focusing on the presentation given that sanity has their own editor.

**Comment by kmelve** [comment]
Hi! We have open-sourced and documented the standalone Portable Text Editor. [Read more about it here](https://www.sanity.io/blog/a-block-content-editor-that-loves-you-back).
